apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-enforcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-enforcer
  template:
    metadata:
      labels:
        app: git-enforcer
    spec:
      containers:
        - name: git-workflow-enforcer
          image: git-workflow-enforcer:latest
          imagePullPolicy: Never
          args: ["--ci", "validate-all"]